### ISSUE TITLE
Is there any way to slim down this library? When I used pod install in ios, the library was so large that the download was slow.

### ISSUE THREAD

**Issue by arden** [topfreegames/libpitaya#13]
Is there any way to slim down this library? When I used “pod install” in ios, the library was so large that the download was slow.

**Comment by leohahn** [comment]
are you using the ios project in this repository? The library itself is not that large, so I do not think this is the issue (around 3.1MB compiled for iOS counting libuv).

**Comment by arden** [comment]
I found out because openssl is so big for ios.

**Comment by leohahn** [comment]
Yes, but one important thing to realize is that the libraries on iOS are static. That means the size of the library is going to go down after linking the app, since the linker will remove parts of the library that you don't use. So to reliably see the size of the library you have to compare the size of the IPA.

**Comment by leohahn** [comment]
I am closing the comment due to inactivity
