### ISSUE TITLE
support protobuf?

### ISSUE THREAD

**Issue by arden** [topfreegames/libpitaya#4]
this client lib can be support protobuf?

**Comment by leohahn** [comment]
Yes, there is support for protobuf. I'll put this info on the readme.

**Comment by leohahn** [comment]
Here you can find more information about the usage of the lib: `https://github.com/topfreegames/libpitaya/blob/master/unity/PitayaExample/Assets/Pitaya/README.md`.

The native library does not directly support protobuf. However, you can send any kind of binary data in a request, for example, including a serialized protobuf class. You can have some idea of how to do that by looking at the tests in `test/test_protobuf.c`.

We decided not to add protobuf support directly in the C library since generally you want to generate the protobuf classes in the language you are writing your app.

**Comment by felipejfc** [comment]
We could add examples of how to use the lib with protobuf support and then close this issue

**Comment by guthyerrz** [comment]
Protobuf example have been added to the iOS example project. You can find them [here](https://github.com/topfreegames/libpitaya/blob/462abe86548795f89255ab98cc630c421c760791/ios/PitayaClient/PitayaClientTests/PitayaClientTests.m#L101)
